/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { ThreeModelProps, GLTFResult } from "./types";

export function ThreeCoffee({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="coffee"
        position={[-153.707, -59.993, 306.082]}
        rotation={[0.146, -0.041, -0.274]}
        scale={0.857}
      >
        <mesh
          name="Coffee0"
          castShadow
          receiveShadow
          geometry={nodes.Coffee0.geometry}
          material={material ?? nodes.Coffee0.material}
          position={[-14.558, 41.512, 5.447]}
          rotation={[0.261, 0.023, 0.084]}
        />
        <mesh
          name="Coffee1"
          castShadow
          receiveShadow
          geometry={nodes.Coffee1.geometry}
          material={material ?? nodes.Coffee1.material}
          position={[0, 18.907, 0]}
        />
        <mesh
          name="Coffee2"
          castShadow
          receiveShadow
          geometry={nodes.Coffee2.geometry}
          material={material ?? nodes.Coffee2.material}
          position={[-0.393, -30.221, -1.028]}
        />
        <mesh
          name="Coffee3"
          castShadow
          receiveShadow
          geometry={nodes.Coffee3.geometry}
          material={material ?? nodes.Coffee3.material}
          position={[-0.393, -37.79, -1.028]}
        />
      </group>
    </group>
  );
}

export function ThreeLifebuoy({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="Lifebuoy"
        position={[368.859, -246.678, -203.913]}
        rotation={[-0.146, -0.439, -0.767]}
        scale={0.901}
      >
        <mesh
          name="Lifebuoy0"
          castShadow
          receiveShadow
          geometry={nodes.Lifebuoy0.geometry}
          material={material ?? nodes.Lifebuoy0.material}
          rotation={[0, 0, -0.262]}
        />
        <mesh
          name="Lifebuoy1"
          castShadow
          receiveShadow
          geometry={nodes.Lifebuoy1.geometry}
          material={material ?? nodes.Lifebuoy1.material}
          rotation={[0, 0, -1.833]}
        />
        <mesh
          name="Lifebuoy2"
          castShadow
          receiveShadow
          geometry={nodes.Lifebuoy2.geometry}
          material={material ?? nodes.Lifebuoy2.material}
          rotation={[0, 0, 2.88]}
        />
        <mesh
          name="Lifebuoy3"
          castShadow
          receiveShadow
          geometry={nodes.Lifebuoy3.geometry}
          material={material ?? nodes.Lifebuoy3.material}
          rotation={[0, 0, 1.309]}
        />
        <mesh
          name="Lifebuoy4"
          castShadow
          receiveShadow
          geometry={nodes.Lifebuoy4.geometry}
          material={material ?? nodes.Lifebuoy4.material}
          rotation={[0, 0, -Math.PI / 3]}
        />
        <mesh
          name="Lifebuoy5"
          castShadow
          receiveShadow
          geometry={nodes.Lifebuoy5.geometry}
          material={material ?? nodes.Lifebuoy5.material}
          rotation={[0, 0, -2.618]}
        />
        <mesh
          name="Lifebuoy6"
          castShadow
          receiveShadow
          geometry={nodes.Lifebuoy6.geometry}
          material={material ?? nodes.Lifebuoy6.material}
          rotation={[0, 0, 2.094]}
        />
        <mesh
          name="Lifebuoy7"
          castShadow
          receiveShadow
          geometry={nodes.Lifebuoy7.geometry}
          material={material ?? nodes.Lifebuoy7.material}
          rotation={[0, 0, Math.PI / 6]}
        />
      </group>
    </group>
  );
}

export function ThreeBeaker({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="beaker"
        position={[-422.26, 12.062, 41.738]}
        rotation={[0.692, 0.285, 0.493]}
        scale={0.84}
      >
        <mesh
          name="Beaker0"
          castShadow
          receiveShadow
          geometry={nodes.Beaker0.geometry}
          material={material ?? nodes.Beaker0.material}
          position={[0.64, -45.332, 0.71]}
        />
        <mesh
          name="Beaker1"
          castShadow
          receiveShadow
          geometry={nodes.Beaker1.geometry}
          material={material ?? nodes.Beaker1.material}
          position={[0, -13.667, 0]}
        />
      </group>
    </group>
  );
}

export function ThreeCard({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="card"
        position={[-275.5, -150.001, 329.713]}
        rotation={[-0.411, -0.215, -0.22]}
        scale={0.78}
      >
        <mesh
          name="Card0"
          castShadow
          receiveShadow
          geometry={nodes.Card0.geometry}
          material={material ?? nodes.Card0.material}
          position={[-39.239, 0.912, 0.479]}
        />
        <mesh
          name="Card1"
          castShadow
          receiveShadow
          geometry={nodes.Card1.geometry}
          material={material ?? nodes.Card1.material}
          position={[-39.239, 10.75, 2.073]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="Card2"
          castShadow
          receiveShadow
          geometry={nodes.Card2.geometry}
          material={material ?? nodes.Card2.material}
          position={[-39.239, 11.051, 0.479]}
        />
        <mesh
          name="Card3"
          castShadow
          receiveShadow
          geometry={nodes.Card3.geometry}
          material={material ?? nodes.Card3.material}
          position={[-39.239, 21.5, 0.479]}
        />
        <mesh
          name="Card4"
          castShadow
          receiveShadow
          geometry={nodes.Card4.geometry}
          material={material ?? nodes.Card4.material}
          position={[-57.889, -24.247, 0.479]}
        />
        <mesh
          name="Card5"
          castShadow
          receiveShadow
          geometry={nodes.Card5.geometry}
          material={material ?? nodes.Card5.material}
          position={[-32.79, -36.18, 0.479]}
        />
        <mesh
          name="Card6"
          castShadow
          receiveShadow
          geometry={nodes.Card6.geometry}
          material={material ?? nodes.Card6.material}
          position={[47.393, -27.436, 0.486]}
        />
        <mesh
          name="Card7"
          castShadow
          receiveShadow
          geometry={nodes.Card7.geometry}
          material={material ?? nodes.Card7.material}
          position={[27.75, -27.436, 0.486]}
        />
        <mesh
          name="Card8"
          castShadow
          receiveShadow
          geometry={nodes.Card8.geometry}
          material={material ?? nodes.Card8.material}
          position={[0, 0, -6.073]}
        />
        <group position={[-57.889, -24.247, 0.479]}>
          <mesh
            name="mesh_18_instance_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh_18_instance_1.geometry}
            material={material ?? nodes.mesh_18_instance_1.material}
          />
          <mesh
            name="mesh_18_instance_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh_18_instance_2.geometry}
            material={material ?? nodes.mesh_18_instance_2.material}
            position={[10, 0, 0]}
          />
          <mesh
            name="mesh_18_instance_3"
            castShadow
            receiveShadow
            geometry={nodes.mesh_18_instance_3.geometry}
            material={material ?? nodes.mesh_18_instance_3.material}
            position={[20, 0, 0]}
          />
          <mesh
            name="mesh_18_instance_4"
            castShadow
            receiveShadow
            geometry={nodes.mesh_18_instance_4.geometry}
            material={material ?? nodes.mesh_18_instance_4.material}
            position={[30, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

export function ThreeTrophy({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="trophy"
        position={[-381.156, 221.257, -331.516]}
        rotation={[-0.086, -0.127, 0.442]}
        scale={[1.927, 1.849, 1.899]}
      >
        <mesh
          name="Trophy0"
          castShadow
          receiveShadow
          geometry={nodes.Trophy0.geometry}
          material={material ?? nodes.Trophy0.material}
          position={[0.709, 35.733, 40.727]}
          rotation={[1.924, 0, 0]}
        />
        <mesh
          name="Trophy1"
          castShadow
          receiveShadow
          geometry={nodes.Trophy1.geometry}
          material={material ?? nodes.Trophy1.material}
          position={[0.599, 36.024, 37.546]}
          rotation={[0.353, 0, 0]}
        />
        <mesh
          name="Trophy2"
          castShadow
          receiveShadow
          geometry={nodes.Trophy2.geometry}
          material={material ?? nodes.Trophy2.material}
          position={[-0.189, -68.822, 0.199]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          name="Trophy3"
          castShadow
          receiveShadow
          geometry={nodes.Trophy3.geometry}
          material={material ?? nodes.Trophy3.material}
          position={[-59.183, 25.535, -1.283]}
          rotation={[0, 0, Math.PI / 6]}
          scale={[-1, 1, 1]}
        />
        <mesh
          name="Trophy4"
          castShadow
          receiveShadow
          geometry={nodes.Trophy4.geometry}
          material={material ?? nodes.Trophy4.material}
          position={[59.183, 26.262, -1.283]}
          rotation={[0, 0, -Math.PI / 6]}
        />
        <mesh
          name="Trophy5"
          castShadow
          receiveShadow
          geometry={nodes.Trophy5.geometry}
          material={material ?? nodes.Trophy5.material}
          position={[-0.21, 34.233, 0]}
        />
      </group>
    </group>
  );
}

export function ThreeDiscount({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="Discount"
        position={[-21.072, -169.972, -54.631]}
        rotation={[0, 0, 0.259]}
        scale={0.964}
      >
        <group
          name="Group_26"
          position={[-3.716, 0, -16.395]}
          rotation={[0.087, 0, -Math.PI / 9]}
        >
          <mesh
            name="Discount1"
            castShadow
            receiveShadow
            geometry={nodes.Discount1.geometry}
            material={material ?? nodes.Discount1.material}
            position={[-27.198, -43.343, 1.563]}
          />
          <mesh
            name="Discount2"
            castShadow
            receiveShadow
            geometry={nodes.Discount2.geometry}
            material={material ?? nodes.Discount2.material}
            position={[-27.198, -43.343, 1.563]}
          />
          <mesh
            name="Discount3"
            castShadow
            receiveShadow
            geometry={nodes.Discount3.geometry}
            material={material ?? nodes.Discount3.material}
            position={[-27.198, -43.343, 1.563]}
          />
          <mesh
            name="Discount0"
            castShadow
            receiveShadow
            geometry={nodes.Discount0.geometry}
            material={material ?? nodes.Discount0.material}
            position={[-41.286, -75.022, -5.563]}
          />
        </group>
        <group
          name="Group_25"
          position={[20.388, -1.29, 10.577]}
          rotation={[-0.174, -0.023, 0.084]}
        >
          <mesh
            name="Discount4"
            castShadow
            receiveShadow
            geometry={nodes.Discount4.geometry}
            material={material ?? nodes.Discount4.material}
            position={[0.864, 58.75, 3.106]}
          />
          <mesh
            name="Discount5"
            castShadow
            receiveShadow
            geometry={nodes.Discount5.geometry}
            material={material ?? nodes.Discount5.material}
            position={[0.864, 58.75, 2.587]}
          />
          <mesh
            name="Discount6"
            castShadow
            receiveShadow
            geometry={nodes.Discount6.geometry}
            material={material ?? nodes.Discount6.material}
            position={[-27.198, -43.343, 1.563]}
          />
          <mesh
            name="Discount7"
            castShadow
            receiveShadow
            geometry={nodes.Discount7.geometry}
            material={material ?? nodes.Discount7.material}
            position={[-27.198, -43.343, 1.563]}
          />
          <mesh
            name="Discount8"
            castShadow
            receiveShadow
            geometry={nodes.Discount8.geometry}
            material={material ?? nodes.Discount8.material}
            position={[-27.198, -43.343, 1.563]}
          />
          <mesh
            name="Discount9"
            castShadow
            receiveShadow
            geometry={nodes.Discount9.geometry}
            material={material ?? nodes.Discount9.material}
            position={[-41.286, -75.022, -5.563]}
          />
        </group>
      </group>
    </group>
  );
}

export function ThreeSpeaker({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="speaker"
        position={[-21.787, 134.603, 120.344]}
        rotation={[-0.553, 0.738, -0.828]}
        scale={[2.423, 2.423, 2.425]}
      >
        <mesh
          name="Speaker0"
          castShadow
          receiveShadow
          geometry={nodes.Speaker0.geometry}
          material={material ?? nodes.Speaker0.material}
          position={[38.239, 1.889, -54.328]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          name="Speaker1"
          castShadow
          receiveShadow
          geometry={nodes.Speaker1.geometry}
          material={material ?? nodes.Speaker1.material}
          position={[0.685, 1.653, -56.203]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Speaker2"
          castShadow
          receiveShadow
          geometry={nodes.Speaker2.geometry}
          material={material ?? nodes.Speaker2.material}
          position={[-0.023, 3.797, 12.503]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Speaker3"
          castShadow
          receiveShadow
          geometry={nodes.Speaker3.geometry}
          material={material ?? nodes.Speaker3.material}
          position={[1.164, 3.036, 37.716]}
          scale={0.73}
        />
        <mesh
          name="Speaker4"
          castShadow
          receiveShadow
          geometry={nodes.Speaker4.geometry}
          material={material ?? nodes.Speaker4.material}
          position={[1.366, 2.13, -35.253]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.73}
        />
      </group>
    </group>
  );
}

export function ThreeCompass({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="compass"
        position={[354.927, 276.527, 26.82]}
        rotation={[0.106, -0.043, -0.389]}
        scale={1.096}
      >
        <mesh
          name="Compass0"
          castShadow
          receiveShadow
          geometry={nodes.Compass0.geometry}
          material={material ?? nodes.Compass0.material}
          position={[-3.293, -21.94, 9.43]}
          rotation={[-0.004, 0.002, 2.618]}
        />
        <mesh
          name="Compass1"
          castShadow
          receiveShadow
          geometry={nodes.Compass1.geometry}
          material={material ?? nodes.Compass1.material}
          position={[3.544, -10.06, 9.43]}
          rotation={[0, 0, -Math.PI / 6]}
        />
        <mesh
          name="Compass2"
          castShadow
          receiveShadow
          geometry={nodes.Compass2.geometry}
          material={material ?? nodes.Compass2.material}
          position={[0.005, -18.081, 1.54]}
        />
        <mesh
          name="Compass3"
          castShadow
          receiveShadow
          geometry={nodes.Compass3.geometry}
          material={material ?? nodes.Compass3.material}
          position={[0.265, -17.692, 0.103]}
        />
        <mesh
          name="Compass4"
          castShadow
          receiveShadow
          geometry={nodes.Compass4.geometry}
          material={material ?? nodes.Compass4.material}
          position={[-0.155, 43.325, 0.605]}
        />
        <mesh
          name="Compass5"
          castShadow
          receiveShadow
          geometry={nodes.Compass5.geometry}
          material={material ?? nodes.Compass5.material}
          position={[-0.155, 49.042, 0.605]}
        />
        <mesh
          name="Compass6"
          castShadow
          receiveShadow
          geometry={nodes.Compass6.geometry}
          material={material ?? nodes.Compass6.material}
          position={[-0.178, 67.16, 0.528]}
        />
        <mesh
          name="Compass7"
          castShadow
          receiveShadow
          geometry={nodes.Compass7.geometry}
          material={material ?? nodes.Compass7.material}
          position={[0, -19.636, -4.772]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.408}
        />
        <group position={[0.005, -18.081, 1.54]}>
          <mesh
            name="mesh_46_instance_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_1.geometry}
            material={material ?? nodes.mesh_46_instance_1.material}
            position={[0, 40, 0]}
          />
          <mesh
            name="mesh_46_instance_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_2.geometry}
            material={material ?? nodes.mesh_46_instance_2.material}
            position={[20, 34.641, 0]}
            rotation={[0, 0, -Math.PI / 6]}
          />
          <mesh
            name="mesh_46_instance_3"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_3.geometry}
            material={material ?? nodes.mesh_46_instance_3.material}
            position={[34.641, 20, 0]}
            rotation={[0, 0, -Math.PI / 3]}
          />
          <mesh
            name="mesh_46_instance_4"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_4.geometry}
            material={material ?? nodes.mesh_46_instance_4.material}
            position={[40, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="mesh_46_instance_5"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_5.geometry}
            material={material ?? nodes.mesh_46_instance_5.material}
            position={[34.641, -20, 0]}
            rotation={[0, 0, -2.094]}
          />
          <mesh
            name="mesh_46_instance_6"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_6.geometry}
            material={material ?? nodes.mesh_46_instance_6.material}
            position={[20, -34.641, 0]}
            rotation={[0, 0, -2.618]}
          />
          <mesh
            name="mesh_46_instance_7"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_7.geometry}
            material={material ?? nodes.mesh_46_instance_7.material}
            position={[0, -40, 0]}
            rotation={[0, 0, -Math.PI]}
          />
          <mesh
            name="mesh_46_instance_8"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_8.geometry}
            material={material ?? nodes.mesh_46_instance_8.material}
            position={[-20, -34.641, 0]}
            rotation={[0, 0, 2.618]}
          />
          <mesh
            name="mesh_46_instance_9"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_9.geometry}
            material={material ?? nodes.mesh_46_instance_9.material}
            position={[-34.641, -20, 0]}
            rotation={[0, 0, 2.094]}
          />
          <mesh
            name="mesh_46_instance_10"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_10.geometry}
            material={material ?? nodes.mesh_46_instance_10.material}
            position={[-40, 0, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            name="mesh_46_instance_11"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_11.geometry}
            material={material ?? nodes.mesh_46_instance_11.material}
            position={[-34.641, 20, 0]}
            rotation={[0, 0, Math.PI / 3]}
          />
          <mesh
            name="mesh_46_instance_12"
            castShadow
            receiveShadow
            geometry={nodes.mesh_46_instance_12.geometry}
            material={material ?? nodes.mesh_46_instance_12.material}
            position={[-20, 34.641, 0]}
            rotation={[0, 0, Math.PI / 6]}
          />
        </group>
        <group position={[0.265, -17.692, 0.103]}>
          <mesh
            name="mesh_47_instance_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh_47_instance_1.geometry}
            material={material ?? nodes.mesh_47_instance_1.material}
            position={[0, 40, 0]}
          />
          <mesh
            name="mesh_47_instance_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh_47_instance_2.geometry}
            material={material ?? nodes.mesh_47_instance_2.material}
            position={[40, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="mesh_47_instance_3"
            castShadow
            receiveShadow
            geometry={nodes.mesh_47_instance_3.geometry}
            material={material ?? nodes.mesh_47_instance_3.material}
            position={[0, -40, 0]}
            rotation={[0, 0, -Math.PI]}
          />
          <mesh
            name="mesh_47_instance_4"
            castShadow
            receiveShadow
            geometry={nodes.mesh_47_instance_4.geometry}
            material={material ?? nodes.mesh_47_instance_4.material}
            position={[-40, 0, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
      </group>
    </group>
  );
}

export function ThreeCalculator({
  material,
  objRef,
  ...props
}: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="calculator"
        position={[434.165, -72.626, 131.85]}
        rotation={[-Math.PI / 4, 0.193, 0]}
        scale={0.848}
      >
        <mesh
          name="Calculator0"
          castShadow
          receiveShadow
          geometry={nodes.Calculator0.geometry}
          material={material ?? nodes.Calculator0.material}
          position={[-22.816, 11.699, -3.376]}
        />
        <mesh
          name="Calculator1"
          castShadow
          receiveShadow
          geometry={nodes.Calculator1.geometry}
          material={material ?? nodes.Calculator1.material}
          position={[38.836, 11.699, -3.376]}
        />
        <mesh
          name="Calculator2"
          castShadow
          receiveShadow
          geometry={nodes.Calculator2.geometry}
          material={material ?? nodes.Calculator2.material}
          position={[14.508, 11.699, -3.376]}
        />
        <mesh
          name="Calculator3"
          castShadow
          receiveShadow
          geometry={nodes.Calculator3.geometry}
          material={material ?? nodes.Calculator3.material}
          position={[-34.132, -13.445, -3.376]}
        />
        <mesh
          name="Calculator4"
          castShadow
          receiveShadow
          geometry={nodes.Calculator4.geometry}
          material={material ?? nodes.Calculator4.material}
          position={[-34.132, -38.073, -3.376]}
        />
        <mesh
          name="Calculator5"
          castShadow
          receiveShadow
          geometry={nodes.Calculator5.geometry}
          material={material ?? nodes.Calculator5.material}
          position={[-34.132, -63.961, -3.376]}
        />
        <mesh
          name="Calculator6"
          castShadow
          receiveShadow
          geometry={nodes.Calculator6.geometry}
          material={material ?? nodes.Calculator6.material}
          position={[-0.468, 53.943, 8.312]}
          rotation={[0.698, 0, 0]}
          scale={[1, 0.852, 1]}
        />
        <mesh
          name="Calculator7"
          castShadow
          receiveShadow
          geometry={nodes.Calculator7.geometry}
          material={material ?? nodes.Calculator7.material}
          position={[0, -26.244, -15.034]}
        />
        <group position={[-34.132, -13.445, -3.376]}>
          <mesh
            name="mesh_55_instance_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh_55_instance_1.geometry}
            material={material ?? nodes.mesh_55_instance_1.material}
          />
          <mesh
            name="mesh_55_instance_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh_55_instance_2.geometry}
            material={material ?? nodes.mesh_55_instance_2.material}
            position={[24.2, 0, 0]}
          />
          <mesh
            name="mesh_55_instance_3"
            castShadow
            receiveShadow
            geometry={nodes.mesh_55_instance_3.geometry}
            material={material ?? nodes.mesh_55_instance_3.material}
            position={[48.4, 0, 0]}
          />
          <mesh
            name="mesh_55_instance_4"
            castShadow
            receiveShadow
            geometry={nodes.mesh_55_instance_4.geometry}
            material={material ?? nodes.mesh_55_instance_4.material}
            position={[72.6, 0, 0]}
          />
        </group>
        <group position={[-34.132, -38.073, -3.376]}>
          <mesh
            name="mesh_56_instance_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh_56_instance_1.geometry}
            material={material ?? nodes.mesh_56_instance_1.material}
          />
          <mesh
            name="mesh_56_instance_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh_56_instance_2.geometry}
            material={material ?? nodes.mesh_56_instance_2.material}
            position={[24.2, 0, 0]}
          />
          <mesh
            name="mesh_56_instance_3"
            castShadow
            receiveShadow
            geometry={nodes.mesh_56_instance_3.geometry}
            material={material ?? nodes.mesh_56_instance_3.material}
            position={[48.4, 0, 0]}
          />
          <mesh
            name="mesh_56_instance_4"
            castShadow
            receiveShadow
            geometry={nodes.mesh_56_instance_4.geometry}
            material={material ?? nodes.mesh_56_instance_4.material}
            position={[72.6, 0, 0]}
          />
        </group>
        <group position={[-34.132, -63.961, -3.376]}>
          <mesh
            name="mesh_57_instance_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh_57_instance_1.geometry}
            material={material ?? nodes.mesh_57_instance_1.material}
          />
          <mesh
            name="mesh_57_instance_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh_57_instance_2.geometry}
            material={material ?? nodes.mesh_57_instance_2.material}
            position={[24.2, 0, 0]}
          />
          <mesh
            name="mesh_57_instance_3"
            castShadow
            receiveShadow
            geometry={nodes.mesh_57_instance_3.geometry}
            material={material ?? nodes.mesh_57_instance_3.material}
            position={[48.4, 0, 0]}
          />
          <mesh
            name="mesh_57_instance_4"
            castShadow
            receiveShadow
            geometry={nodes.mesh_57_instance_4.geometry}
            material={material ?? nodes.mesh_57_instance_4.material}
            position={[72.6, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

export function ThreeFolder({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="folder"
        position={[-171.728, 408.832, -94.503]}
        rotation={[0.65, 0, 0.342]}
        scale={0.817}
      >
        <mesh
          name="Folder0"
          castShadow
          receiveShadow
          geometry={nodes.Folder0.geometry}
          material={material ?? nodes.Folder0.material}
          position={[7.43, 7, -5.778]}
          rotation={[0.262, 0, 0]}
        />
        <mesh
          name="Folder1"
          castShadow
          receiveShadow
          geometry={nodes.Folder1.geometry}
          material={material ?? nodes.Folder1.material}
          position={[-0.488, 19.27, -11.595]}
          rotation={[0.175, 0, 0]}
        />
        <mesh
          name="Folder2"
          castShadow
          receiveShadow
          geometry={nodes.Folder2.geometry}
          material={material ?? nodes.Folder2.material}
          position={[4.02, 21.125, -19.934]}
          rotation={[0.087, 0, 0]}
        />
        <mesh
          name="Folder3"
          castShadow
          receiveShadow
          geometry={nodes.Folder3.geometry}
          material={material ?? nodes.Folder3.material}
          position={[-0.93, -3.883, -29.724]}
        />
      </group>
    </group>
  );
}

export function ThreeHandle({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="handle"
        position={[226.503, -92.646, -248.417]}
        rotation={[-0.152, -0.571, 0.333]}
        scale={1.208}
      >
        <mesh
          name="Handle0"
          castShadow
          receiveShadow
          geometry={nodes.Handle0.geometry}
          material={material ?? nodes.Handle0.material}
          position={[3.403, 20.39, 24.575]}
        />
        <mesh
          name="Handle1"
          castShadow
          receiveShadow
          geometry={nodes.Handle1.geometry}
          material={material ?? nodes.Handle1.material}
          position={[62.727, 56.828, 7.856]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Handle2"
          castShadow
          receiveShadow
          geometry={nodes.Handle2.geometry}
          material={material ?? nodes.Handle2.material}
          position={[-59.245, 56.828, 7.856]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Handle3"
          castShadow
          receiveShadow
          geometry={nodes.Handle3.geometry}
          material={material ?? nodes.Handle3.material}
          position={[64.767, 29.28, 28.536]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Handle4"
          castShadow
          receiveShadow
          geometry={nodes.Handle4.geometry}
          material={material ?? nodes.Handle4.material}
          position={[51.914, 16.122, 28.536]}
        />
        <mesh
          name="Handle5"
          castShadow
          receiveShadow
          geometry={nodes.Handle5.geometry}
          material={material ?? nodes.Handle5.material}
          position={[38.451, 29.28, 28.536]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Handle6"
          castShadow
          receiveShadow
          geometry={nodes.Handle6.geometry}
          material={material ?? nodes.Handle6.material}
          position={[51.914, 42.438, 28.536]}
        />
        <mesh
          name="Handle7"
          castShadow
          receiveShadow
          geometry={nodes.Handle7.geometry}
          material={material ?? nodes.Handle7.material}
          position={[-36.568, 29.282, 28.536]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Handle8"
          castShadow
          receiveShadow
          geometry={nodes.Handle8.geometry}
          material={material ?? nodes.Handle8.material}
          position={[-48.964, 16.886, 28.536]}
        />
        <mesh
          name="Handle9"
          castShadow
          receiveShadow
          geometry={nodes.Handle9.geometry}
          material={material ?? nodes.Handle9.material}
          position={[-61.36, 29.282, 28.536]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Handle10"
          castShadow
          receiveShadow
          geometry={nodes.Handle10.geometry}
          material={material ?? nodes.Handle10.material}
          position={[-48.964, 41.678, 28.536]}
        />
        <mesh
          name="Handle11"
          castShadow
          receiveShadow
          geometry={nodes.Handle11.geometry}
          material={material ?? nodes.Handle11.material}
          position={[51.609, 28.678, 27.456]}
        />
        <mesh
          name="Handle12"
          castShadow
          receiveShadow
          geometry={nodes.Handle12.geometry}
          material={material ?? nodes.Handle12.material}
          position={[-48.932, 28.678, 27.456]}
        />
        <mesh
          name="Handle13"
          castShadow
          receiveShadow
          geometry={nodes.Handle13.geometry}
          material={material ?? nodes.Handle13.material}
          position={[51.609, 28.678, 26.381]}
        />
        <mesh
          name="Handle14"
          castShadow
          receiveShadow
          geometry={nodes.Handle14.geometry}
          material={material ?? nodes.Handle14.material}
          position={[-48.932, 28.678, 26.381]}
        />
        <mesh
          name="Handle15"
          castShadow
          receiveShadow
          geometry={nodes.Handle15.geometry}
          material={material ?? nodes.Handle15.material}
          position={[-0.019, 26.935, -4.206]}
        />
      </group>
    </group>
  );
}

export function ThreeBell({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="bell"
        position={[477.859, 102.227, -386.445]}
        rotation={[0.054, 0.26, -0.171]}
        scale={1.104}
      >
        <mesh
          name="Bell0"
          castShadow
          receiveShadow
          geometry={nodes.Bell0.geometry}
          material={material ?? nodes.Bell0.material}
          position={[-0.063, 61.044, -4.111]}
        />
        <mesh
          name="Bell1"
          castShadow
          receiveShadow
          geometry={nodes.Bell1.geometry}
          material={material ?? nodes.Bell1.material}
          position={[0.506, -55.049, 1.477]}
          scale={1.224}
        />
        <mesh
          name="Bell2"
          castShadow
          receiveShadow
          geometry={nodes.Bell2.geometry}
          material={material ?? nodes.Bell2.material}
          position={[0, 3.395, 0]}
        />
      </group>
    </group>
  );
}

export function ThreeCamera({ material, objRef, ...props }: ThreeModelProps) {
  const { nodes } = useGLTF("/icons.glb") as GLTFResult;
  return (
    <group ref={objRef} {...props} dispose={null} scale={0.02}>
      <group
        name="camera"
        position={[189.3, 346.836, 53.877]}
        rotation={[0.446, 0.24, 0.328]}
        scale={0.825}
      >
        <mesh
          name="Camera0"
          castShadow
          receiveShadow
          geometry={nodes.Camera0.geometry}
          material={material ?? nodes.Camera0.material}
          position={[-0.943, -8.885, -21.999]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          name="Camera1"
          castShadow
          receiveShadow
          geometry={nodes.Camera1.geometry}
          material={material ?? nodes.Camera1.material}
          position={[48.373, 20.391, 12.125]}
        />
        <mesh
          name="Camera2"
          castShadow
          receiveShadow
          geometry={nodes.Camera2.geometry}
          material={material ?? nodes.Camera2.material}
          position={[1.5, -9.742, 26.546]}
        />
        <mesh
          name="Camera3"
          castShadow
          receiveShadow
          geometry={nodes.Camera3.geometry}
          material={material ?? nodes.Camera3.material}
          position={[0, -8.742, -7.589]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/icons.glb");
