/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sejR9QiJNcY
 */
import { ResponsivePie } from "@nivo/pie";
import { ComponentPropsWithoutRef } from "react";

type PieChartProps = {
  data: { id: string; value: number }[];
} & ComponentPropsWithoutRef<"div">;

export function PieChart({ data, ...props }: PieChartProps) {
  return (
    <div {...props}>
      <ResponsivePie
        data={data}
        sortByValue
        margin={{ top: 10, right: 10, bottom: 10, left: 10 }}
        cornerRadius={0}
        padAngle={0}
        borderWidth={1}
        borderColor={"#ffffff"}
        enableArcLinkLabels={true}
        arcLabel={(d) => `${d.id}`}
        arcLabelsTextColor={"#ffffff"}
        arcLabelsRadiusOffset={0.65}
        colors={["#2563eb"]}
        theme={{
          labels: {
            text: {
              fontSize: "18px",
            },
          },
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
        }}
        role="application"
      />
    </div>
  );
}
