/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sejR9QiJNcY
 */
import { PieSvgProps, ResponsivePie } from "@nivo/pie";

type PieChartProps = {
  data: { id: string; value: number }[];
  colors?: string[];
} & Omit<PieSvgProps<{ id: string; value: number }>, "width" | "height">;

export function PieChart({ data, colors, ...props }: PieChartProps) {
  return (
    <ResponsivePie
      data={data}
      sortByValue
      margin={{ top: 4, right: 4, bottom: 4, left: 4 }}
      cornerRadius={0}
      padAngle={0}
      borderWidth={1}
      borderColor={"#ffffff"}
      arcLabel={(d) => `${d.id}`}
      arcLabelsTextColor={"#ffffff"}
      arcLabelsRadiusOffset={0.65}
      colors={colors ?? ["var(--color-primary)", "var(--color-secondary)"]}
      theme={{
        labels: {
          text: {
            fontSize: "10px",
          },
        },
        tooltip: {
          chip: {
            borderRadius: "9999px",
          },
          container: {
            fontSize: "12px",
            textTransform: "capitalize",
            borderRadius: "6px",
          },
        },
      }}
      role="application"
      {...props}
    />
  );
}
